name: Matrix Workflow
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [14, 16, 18] # Define Node.js versions
        os: [ubuntu-latest, windows-latest, macos-latest] # Define OS types
        includes: # Combine Node.js versions with OS types
          - node-version: 12
            os: ubuntu-latest
        exclude: # Exclude unsupported combinations
          - node-version: 14
            os: macos-latest    
         
    runs-on: ${{ matrix.os }} # Use OS from matrix
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} # Use Node.js version from matrix
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build